// Generated by CoffeeScript 1.8.0
(function() {
  var apiUrl, http, testLocation;

  http = require('http');

  testLocation = '33.4213,-111.9427';

  apiUrl = 'https://api.forecast.io/forecast/f256b505c3b676b717e455c54285b08a/';

  http.get({
    host: apiUrl + testLocation
  }, function(err, res, body) {
    return console.log(res.statusCode);
  });

}).call(this);
